// Made by scripts/area-icons.mjs from Lucide 1.48.0: change the list there and run it again.

/*
 * The icons an area can show in its color instead of its dot: Lucide's names, by category in the order the area's
 * menu offers them, with words to find each one by. src/components/area-icon-paths.ts draws them; the data keeps
 * only the name.
 */
export const AREA_ICON_CATEGORIES = [
  { name: "Work", icons: ["briefcase", "briefcase-business", "building", "factory", "landmark", "store", "handshake", "presentation", "chart-line", "chart-column", "chart-pie", "trending-up", "target", "clipboard-list", "clipboard-check", "list-todo", "square-check-big", "kanban", "file-text", "folder", "folder-open", "archive", "inbox", "mail", "send", "calendar", "calendar-days", "calendar-check", "clock", "timer", "alarm-clock", "hourglass", "award", "crown", "scale", "gavel", "stamp", "id-card"] },
  { name: "Tech", icons: ["code", "code-xml", "terminal", "braces", "bug", "git-branch", "git-merge", "git-pull-request", "cpu", "database", "server", "cloud", "cloud-cog", "laptop", "monitor", "smartphone", "tablet", "keyboard", "mouse", "wifi", "globe", "network", "shield", "shield-check", "lock", "key-round", "fingerprint-pattern", "bot", "sparkles", "wand-sparkles", "rocket", "satellite", "radar", "layers", "layout-dashboard", "blocks", "puzzle", "component", "box", "package", "boxes", "hard-drive", "cable", "plug", "battery", "zap", "power", "settings", "wrench", "hammer", "cog", "workflow", "webhook", "qr-code"] },
  { name: "People", icons: ["user", "users", "user-round", "contact", "baby", "heart-handshake", "hand-heart", "face-slightly-smiling", "message-circle", "message-square", "messages-square", "phone", "video", "mic", "megaphone", "bell", "at-sign", "share-2", "rss", "party-popper", "person-standing", "accessibility"] },
  { name: "Learning", icons: ["graduation-cap", "school", "book", "book-open", "book-bookmark", "library", "notebook", "notebook-pen", "pencil", "pen-tool", "highlighter", "languages", "brain", "lightbulb", "microscope", "flask-conical", "atom", "dna", "telescope", "calculator", "sigma", "ruler", "earth", "map", "compass", "glasses", "scroll-text"] },
  { name: "Health", icons: ["heart", "heart-pulse", "activity", "stethoscope", "pill", "syringe", "hospital", "cross", "dumbbell", "bike", "footprints", "apple", "salad", "bed", "eye", "brain-circuit", "thermometer", "bandage", "droplet", "face-grinning"] },
  { name: "Home", icons: ["house", "sofa", "armchair", "lamp", "bath", "shower-head", "key", "door-open", "bed-double", "sprout", "flower", "flower-2", "trees", "tree-pine", "tree-deciduous", "shopping-cart", "shopping-bag", "shirt", "scissors", "washing-machine", "dog", "cat", "paw-print", "fish", "bird", "rabbit", "turtle", "gift", "cake", "calendar-heart", "paint-roller", "trash", "recycle"] },
  { name: "Food", icons: ["utensils", "utensils-crossed", "chef-hat", "cooking-pot", "soup", "coffee", "cup-soda", "wine", "beer", "martini", "pizza", "sandwich", "croissant", "ice-cream-cone", "cookie", "egg", "cherry", "grape", "banana", "citrus", "carrot", "popcorn", "candy", "milk"] },
  { name: "Travel", icons: ["plane", "plane-takeoff", "car", "car-taxi-front", "bus", "train-front", "tram-front", "ship", "sailboat", "anchor", "map-pin", "navigation", "route", "signpost", "tent", "caravan", "mountain", "mountain-snow", "tree-palm", "luggage", "ticket", "hotel", "fuel"] },
  { name: "Nature", icons: ["sun", "moon", "cloud-sun", "cloud-rain", "snowflake", "umbrella", "flame", "waves-horizontal", "wind", "rainbow", "sunrise", "sunset", "star", "sparkle", "leaf", "clover", "feather", "shell"] },
  { name: "Money", icons: ["wallet", "piggy-bank", "coins", "banknote", "credit-card", "receipt", "badge-dollar-sign", "dollar-sign", "euro", "percent", "tag", "tags", "gem", "chart-candlestick", "bitcoin", "hand-coins", "vault", "chart-no-axes-combined"] },
  { name: "Media", icons: ["palette", "brush", "paintbrush", "music", "music-2", "headphones", "guitar", "piano", "camera", "image", "film", "clapperboard", "tv", "radio", "mic-vocal", "gamepad-2", "dices", "drama", "book-audio", "disc-3", "speaker", "projector", "aperture"] },
  { name: "Sports", icons: ["trophy", "medal", "volleyball", "goal", "joystick", "flag", "swords", "sword", "dice-5", "spade", "timer-reset"] },
  { name: "Symbols", icons: ["bookmark", "circle", "square", "triangle", "hexagon", "diamond", "octagon", "pentagon", "infinity", "hash", "asterisk", "check", "circle-check", "badge", "sun-moon", "moon-star", "orbit", "circle-dot", "shapes"] },
] as const;

export type AreaIcon = (typeof AREA_ICON_CATEGORIES)[number]["icons"][number];

export const AREA_ICONS: readonly AreaIcon[] = AREA_ICON_CATEGORIES.flatMap((c) => c.icons);

const known = new Set<string>(AREA_ICONS);

export const isAreaIcon = (v: unknown): v is AreaIcon => typeof v === "string" && known.has(v);

/** An area's icon as stored: null when it has none, or a name this version doesn't draw. */
export const areaIconOf = (v: unknown): AreaIcon | null => (isAreaIcon(v) ? v : null);

/** What an icon is called: its name without Lucide's variant number, such as "Graduation cap". */
export const areaIconLabel = (icon: AreaIcon) => {
  const words = icon.replace(/-\d+$/, "").replace(/-/g, " ");
  return words[0].toUpperCase() + words.slice(1);
};

/** Words each icon can be found by: its name and Lucide's tags. */
export const AREA_ICON_WORDS: Record<AreaIcon, string> = {
  "briefcase": "briefcase work bag baggage folder",
  "briefcase-business": "briefcase business work bag baggage folder portfolio",
  "building": "building organisation organization",
  "factory": "factory building business energy industry manufacture sector",
  "landmark": "landmark bank building capitol finance money museum art gallery hall institute pediment portico doric columns pillars classical architecture government institut",
  "store": "store shop supermarket stand boutique building",
  "handshake": "handshake agreement partnership deal business assistance cooperation friendship union terms",
  "presentation": "presentation screen whiteboard marker pens markers blackboard chalk easel school learning lesson office meeting project planning",
  "chart-line": "chart line statistics analytics diagram graph",
  "chart-column": "chart column statistics analytics diagram graph",
  "chart-pie": "chart pie statistics analytics diagram presentation",
  "trending-up": "trending up statistics",
  "target": "target logo bullseye deadline projects overview work productivity",
  "clipboard-list": "clipboard list copy paste tasks",
  "clipboard-check": "clipboard check copied pasted done todo tick complete task",
  "list-todo": "list todo done check tick complete tasks items pending",
  "square-check-big": "square check big done todo tick complete task",
  "kanban": "kanban projects manage overview board tickets issues roadmap plan intentions productivity work agile code coding",
  "file-text": "file text data txt pdf document",
  "folder": "folder directory",
  "folder-open": "folder open directory",
  "archive": "archive index backup box storage records",
  "inbox": "inbox email",
  "mail": "mail email message letter unread",
  "send": "send email message mail paper airplane paper aeroplane submit",
  "calendar": "calendar date month year event birthday birthdate",
  "calendar-days": "calendar days date month year event",
  "calendar-check": "calendar check date day month year event confirm subscribe schedule done todo tick complete task",
  "clock": "clock time watch alarm",
  "timer": "timer time stopwatch",
  "alarm-clock": "alarm clock morning",
  "hourglass": "hourglass timer time sandglass",
  "award": "award achievement badge rosette prize winner",
  "crown": "crown diadem tiara circlet corona king ruler winner favourite",
  "scale": "scale balance legal license right rule law justice weight measure compare judge fair ethics decision",
  "gavel": "gavel justice law court judgment legal hands penalty decision authority hammer mallet",
  "stamp": "stamp mark print clone loyalty library",
  "id-card": "id card badge identity authentication secure",
  "code": "code source programming html xml",
  "code-xml": "code xml source programming html",
  "terminal": "terminal code command line prompt shell",
  "braces": "braces json code token curly brackets data { }",
  "bug": "bug issue error defect testing troubleshoot problem report debug code insect beetle",
  "git-branch": "git branch code version control vcs repository",
  "git-merge": "git merge code version control",
  "git-pull-request": "git pull request code version control open",
  "cpu": "cpu processor cores technology computer chip circuit memory ram specs gigahertz ghz",
  "database": "database storage memory container tin pot bytes servers",
  "server": "server cloud storage",
  "cloud": "cloud weather",
  "cloud-cog": "cloud cog computing ai cluster network",
  "laptop": "laptop computer screen remote",
  "monitor": "monitor tv computer desktop screen display external display screen sharing virtual machine vm",
  "smartphone": "smartphone phone cellphone device mobile screen display touchscreen portable responsive",
  "tablet": "tablet device mobile screen display touchscreen portable responsive",
  "keyboard": "keyboard layout spell settings mouse",
  "mouse": "mouse device scroll click",
  "wifi": "wifi connection signal wireless",
  "globe": "globe world browser language translate",
  "network": "network tree",
  "shield": "shield cybersecurity secure safety protection guardian armored armoured defense defence defender block threat prevention antivirus vigilance vigilant detection ",
  "shield-check": "shield check cybersecurity secured safety protection protected guardian guarded armored armoured defense defence defended blocked threat prevention prevented an",
  "lock": "lock security password secure admin",
  "key-round": "key round password login authentication secure unlock",
  "fingerprint-pattern": "fingerprint pattern 2fa authentication biometric identity security",
  "bot": "bot robot ai chat assistant",
  "sparkles": "sparkles stars effect filter night magic",
  "wand-sparkles": "wand sparkles magic wizard magician",
  "rocket": "rocket release boost launch space version",
  "satellite": "satellite space station orbit transmitter",
  "radar": "radar scan sonar detect find locate",
  "layers": "layers stack pile pages sheets paperwork copies copy",
  "layout-dashboard": "layout dashboard masonry brick",
  "blocks": "blocks addon plugin integration extension package build stack toys kids children learning squares corner",
  "puzzle": "puzzle component module part piece",
  "component": "component design element group module part symbol",
  "box": "box cube package container storage geometry 3d isometric",
  "package": "package box container storage sealed delivery undelivered unopened packed archive zip module",
  "boxes": "boxes cubes packages parts group units collection cluster geometry",
  "hard-drive": "hard drive computer server memory data ssd disk hard disk storage hardware backup media",
  "cable": "cable cord wire connector connection link signal console computer equipment electricity energy electronics recharging charger power supply disconnected unplugge",
  "plug": "plug electricity energy electronics socket outlet power voltage current charger",
  "battery": "battery power electricity energy accumulator charge",
  "zap": "zap flash camera lightning electricity energy power quick",
  "power": "power on off device switch toggle binary boolean reboot restart button keyboard troubleshoot",
  "settings": "settings cog edit gear preferences",
  "wrench": "wrench account settings spanner diy toolbox build construction",
  "hammer": "hammer mallet nails diy toolbox build construction",
  "cog": "cog computing settings edit gear preferences controls configuration fixed build construction parts",
  "workflow": "workflow action continuous integration ci automation devops network node connection",
  "webhook": "webhook push api interface callback",
  "qr-code": "qr code barcode scan link url information digital",
  "user": "user person account contact",
  "users": "users group people",
  "user-round": "user round person account contact",
  "contact": "contact user person family friend acquaintance listing networking",
  "baby": "baby child childproof children",
  "heart-handshake": "heart handshake agreement charity help deal terms emotion together",
  "hand-heart": "hand heart love like emotion",
  "face-slightly-smiling": "face slightly smiling smile happy happiness good positive friendly patronizing passive aggressive ironic emoji emotion",
  "message-circle": "message circle comment chat conversation dialog feedback speech bubble",
  "message-square": "message square comment chat conversation dialog feedback speech bubble",
  "messages-square": "messages square comment chat conversation dialog feedback speech bubbles copy multiple discussion interview debate",
  "phone": "phone call",
  "video": "video camera movie film recording motion picture camcorder reel",
  "mic": "mic record sound listen radio podcast microphone",
  "megaphone": "megaphone advertisement announcement attention alert loudspeaker notification",
  "bell": "bell alarm notification sound reminder",
  "at-sign": "at sign mention email message @",
  "share-2": "share network connections",
  "rss": "rss feed subscribe news updates notifications content blog articles broadcast syndication reader channels posts publishing digest alert following inbox newslett",
  "party-popper": "party popper emoji congratulations celebration tada 🎉 🎊 excitement exciting excites confetti",
  "person-standing": "person standing people human accessibility stick figure",
  "accessibility": "accessibility disability disabled dda wheelchair",
  "graduation-cap": "graduation cap school university learn study mortarboard education ceremony academic hat diploma bachelor's master's doctorate",
  "school": "school building education childhood university learning campus scholar student lecture degree course academia study knowledge classroom research diploma graduat",
  "book": "book reading paperback booklet magazine leaflet pamphlet tome library writing written writer author story script fiction novel information knowledge education h",
  "book-open": "book open reading pages booklet magazine leaflet pamphlet library writing written writer author story script screenplay fiction novel information knowledge educ",
  "book-bookmark": "book bookmark dictionary reading booklet magazine leaflet pamphlet tome library writing written writer author story script fiction novel information knowledge e",
  "library": "library books reading written authors stories fiction novels information knowledge education high school university college academy learning study research coll",
  "notebook": "notebook notepad notes stationery sketchbook moleskine closure strap band elastic organizer organiser planner diary journal writing written writer reading high ",
  "notebook-pen": "notebook pen pencil notepad notes noted stationery sketchbook organizer organiser planner diary journal writing write written reading high school university col",
  "pencil": "pencil rubber edit create draw sketch draft writer writing stationery artist",
  "pen-tool": "pen tool vector drawing path",
  "highlighter": "highlighter mark text",
  "languages": "languages translate",
  "brain": "brain medical mind mental intellect cerebral consciousness genius artificial intelligence ai think thought insight intelligent smart",
  "lightbulb": "lightbulb idea bright lights",
  "microscope": "microscope medical education science imaging research",
  "flask-conical": "flask conical beaker erlenmeyer lab chemistry experiment test",
  "atom": "atom atomic nuclear physics particle element molecule electricity energy chemistry",
  "dna": "dna gene gmo helix heredity chromosome nucleic acid",
  "telescope": "telescope astronomy space discovery exploration explore vision perspective focus stargazing observe view",
  "calculator": "calculator count calculating machine",
  "sigma": "sigma sum calculate formula math enumeration enumerate",
  "ruler": "ruler measurements centimeters cm millimeters mm metre foot feet inches units size length width height dimensions depth breadth extent stationery",
  "earth": "earth world browser language translate globe",
  "map": "map location navigation travel",
  "compass": "compass direction north east south west browser",
  "glasses": "glasses spectacles",
  "scroll-text": "scroll text paper log scripture document notes parchment list long script story code coding",
  "heart": "heart like love emotion suit playing cards",
  "heart-pulse": "heart pulse heartbeat health medical blood pressure cardiac systole diastole",
  "activity": "activity pulse action motion movement exercise fitness healthcare heart rate monitor vital signs vitals emergency room er intensive care hospital defibrillator ",
  "stethoscope": "stethoscope phonendoscope medical heart lungs sound",
  "pill": "pill medicine medication drug prescription tablet pharmacy",
  "syringe": "syringe medicine medical needle pump plunger nozzle blood",
  "hospital": "hospital infirmary sanatorium healthcare doctor hospice clinic emergency room ward building medical vet",
  "cross": "cross healthcare first aid",
  "dumbbell": "dumbbell barbell weight workout gym",
  "bike": "bike bicycle transport trip",
  "footprints": "footprints steps walking foot feet trail shoe",
  "apple": "apple fruit food healthy snack nutrition fresh produce grocery organic harvest vitamin red green juicy sweet tart bite orchard plant core raw diet",
  "salad": "salad food vegetarian dish restaurant course meal side vegetables health",
  "bed": "bed sleep hotel furniture",
  "eye": "eye view watch see show expose reveal display visible visibility vision preview read",
  "brain-circuit": "brain circuit mind intellect artificial intelligence ai deep learning machine learning computing",
  "thermometer": "thermometer temperature celsius fahrenheit weather",
  "bandage": "bandage plaster band-aid first aid medical health wound injury care treatment healing protection emergency aid safety patch",
  "droplet": "droplet water weather liquid fluid wet moisture damp bead globule",
  "face-grinning": "face grinning happy happiness good laugh broad smile pleasure good cheer humour funny emoji emotion",
  "house": "house home living building residence architecture",
  "sofa": "sofa armchair furniture leisure lounge loveseat couch",
  "armchair": "armchair sofa furniture leisure lounge loveseat couch",
  "lamp": "lamp lighting household home furniture",
  "bath": "bath amenities services bathroom shower",
  "shower-head": "shower head bath bathroom amenities services",
  "key": "key password login authentication secure unlock keychain key ring fob",
  "door-open": "door open entrance entry exit ingress egress gate gateway emergency exit",
  "bed-double": "bed double sleep hotel furniture",
  "sprout": "sprout eco green growth leaf nature plant seed spring sustainability",
  "flower": "flower sustainability nature plant spring",
  "flower-2": "flower sustainability nature plant",
  "trees": "trees tree forest park nature",
  "tree-pine": "tree pine forest park nature",
  "tree-deciduous": "tree deciduous forest park nature",
  "shopping-cart": "shopping cart trolley basket e-commerce store purchase products items ingredients",
  "shopping-bag": "shopping bag ecommerce cart purchase store",
  "shirt": "shirt t-shirt shopping store clothing clothes",
  "scissors": "scissors cut snip chop stationery crafts",
  "washing-machine": "washing machine tumble dryer amenities electronics cycle clothes rinse spin drum",
  "dog": "dog animal pet puppy hound canine",
  "cat": "cat animal pet kitten feline",
  "paw-print": "paw print pets vets veterinarian domesticated cat dog bear",
  "fish": "fish dish restaurant course meal seafood pet sea marine",
  "bird": "bird peace freedom wing avian tweet",
  "rabbit": "rabbit animal rodent pet pest bunny hare fast speed hop",
  "turtle": "turtle animal pet tortoise slow speed",
  "gift": "gift present box birthday party",
  "cake": "cake birthday birthdate celebration party surprise gateaux dessert fondant icing sugar sweet baking",
  "calendar-heart": "calendar heart date month year event favourite subscribe valentines day",
  "paint-roller": "paint roller brush color colour decoration diy",
  "trash": "trash empty deletion cleanup junk clear garbage delete remove bin waste recycle discard binoculars rubbish",
  "recycle": "recycle sustainability salvage arrows",
  "utensils": "utensils fork knife cutlery flatware tableware silverware food restaurant meal breakfast dinner supper",
  "utensils-crossed": "utensils crossed fork knife cutlery flatware tableware silverware food restaurant meal breakfast dinner supper",
  "chef-hat": "chef hat cooking food kitchen restaurant",
  "cooking-pot": "cooking pot pod recipe food kitchen chef restaurant dinner lunch breakfast meal eat",
  "soup": "soup food dish restaurant course meal bowl starter",
  "coffee": "coffee drink cup mug tea cafe hot beverage",
  "cup-soda": "cup soda beverage drink straw water",
  "wine": "wine alcohol beverage bar drink glass sommelier vineyard winery",
  "beer": "beer alcohol bar beverage brewery drink",
  "martini": "martini cocktail alcohol beverage bar drink glass spirit party celebration mixer",
  "pizza": "pizza pie quiche food",
  "sandwich": "sandwich food snack dish restaurant lunch meal",
  "croissant": "croissant bakery cooking food pastry",
  "ice-cream-cone": "ice cream cone gelato food",
  "cookie": "cookie biscuit snack dessert food sweet bakery consent privacy legal tracking browser website",
  "egg": "egg bird chicken nest hatch shell incubate soft boiled hard breakfast brunch morning easter",
  "cherry": "cherry fruit food",
  "grape": "grape fruit wine food",
  "banana": "banana fruit food",
  "citrus": "citrus lemon orange grapefruit fruit",
  "carrot": "carrot orange healthy nature fresh root produce organic nutrition vegetable food eat",
  "popcorn": "popcorn cinema movies films salted sweet sugar candy snack",
  "candy": "candy sugar food sweet",
  "milk": "milk lactose bottle beverage drink water diet",
  "plane": "plane trip airplane",
  "plane-takeoff": "plane takeoff departure trip airplane",
  "car": "car vehicle drive trip journey",
  "car-taxi-front": "car taxi front cab vehicle drive trip journey",
  "bus": "bus vehicle transport trip",
  "train-front": "train front railway metro subway underground high-speed bullet fast track line",
  "tram-front": "tram front railway metro subway underground track line tourism",
  "ship": "ship boat knots nautical mile maritime sailing yacht cruise ocean liner tanker vessel navy trip releases",
  "sailboat": "sailboat ship boat harbor harbour dock",
  "anchor": "anchor ship",
  "map-pin": "map pin location waypoint marker drop",
  "navigation": "navigation location travel",
  "route": "route path journey planner points stops stations",
  "signpost": "signpost navigation direction arrow wayfinding guide location pointer route indicator marker bidirectional left right east west",
  "tent": "tent tipi teepee wigwam lodge camping campsite holiday retreat nomadic native american indian wilderness outdoors",
  "caravan": "caravan trailer tow camping campsite mobile home holiday nomadic wilderness outdoors",
  "mountain": "mountain climb hike rock",
  "mountain-snow": "mountain snow alpine climb",
  "tree-palm": "tree palm vacation leisure island",
  "luggage": "luggage baggage travel suitcase",
  "ticket": "ticket entry pass voucher event concert show perforated dashed",
  "hotel": "hotel building hostel motel inn",
  "fuel": "fuel filling-station gas petrol tank",
  "sun": "sun brightness weather light summer",
  "moon": "moon dark night",
  "cloud-sun": "cloud sun weather partly",
  "cloud-rain": "cloud rain weather rainfall",
  "snowflake": "snowflake cold weather freeze snow winter",
  "umbrella": "umbrella rain weather",
  "flame": "flame heat burn light glow ignite passion ember fire lit burning spark embers smoke firefighter fireman department brigade station emergency",
  "waves-horizontal": "waves horizontal water sea sound hertz wavelength vibrate ocean swimming frequency",
  "wind": "wind weather air blow",
  "rainbow": "rainbow colors colours spectrum light prism arc clear sunshine",
  "sunrise": "sunrise weather time morning day",
  "sunset": "sunset weather time evening night",
  "star": "star bookmark favorite like review rating",
  "sparkle": "sparkle star effect filter night magic shiny glitter twinkle celebration",
  "leaf": "leaf sustainability nature energy plant autumn",
  "clover": "clover leaf luck plant",
  "feather": "feather quill plume writing author literature poetry manuscript bird plumage lightweight soft",
  "shell": "shell beach sand holiday sealife fossil ammonite biology ocean terminal command line session bash zsh roll wrap chewing gum bubble gum sweet sugar hosepipe carp",
  "wallet": "wallet money finance pocket",
  "piggy-bank": "piggy bank money savings",
  "coins": "coins money cash finance gamble",
  "banknote": "banknote currency money payment",
  "credit-card": "credit card bank purchase payment cc",
  "receipt": "receipt bill voucher slip check counterfoil currency dollar usd $",
  "badge-dollar-sign": "badge dollar sign discount offer sale voucher tag monetization marketing finance financial exchange transaction payment usd $",
  "dollar-sign": "dollar sign currency money payment",
  "euro": "euro currency money payment",
  "percent": "percent percentage modulo modulus remainder % sale discount offer marketing",
  "tag": "tag label badge ticket mark",
  "tags": "tags labels badges tickets marks copy multiple",
  "gem": "gem diamond crystal ruby jewellery price special present gift ring wedding proposal marriage rubygems",
  "chart-candlestick": "chart candlestick trading trader financial markets portfolio assets prices value valuation commodities currencies currency stocks exchange hedge fund statistics",
  "bitcoin": "bitcoin cryptocurrency digital blockchain finance coin market decentralized investment crypto currency money payment",
  "hand-coins": "hand coins savings banking money finance offers mortgage payment received wage payroll allowance pocket money handout pennies",
  "vault": "vault safe lockbox deposit locker coffer strongbox safety secure storage valuables bank",
  "chart-no-axes-combined": "chart no axes combined statistics analytics diagram graph trending up",
  "palette": "palette colors colours theme scheme paint watercolor watercolour artist",
  "brush": "brush clean sweep refactor remove draw paint color artist",
  "paintbrush": "paintbrush brush design color colour decoration diy",
  "music": "music note quaver eighth note",
  "music-2": "music quaver eighth note note",
  "headphones": "headphones music audio sound",
  "guitar": "guitar acoustic instrument strings riff rock band country concert performance play lead loud music audio sound noise",
  "piano": "piano music audio sound noise notes chord keys octave acoustic instrument play pianist performance concert",
  "camera": "camera photography lens focus capture shot visual image device equipment photo webcam video",
  "image": "image picture photo",
  "film": "film movie video reel camera cinema entertainment",
  "clapperboard": "clapperboard movie film video camera cinema cut action television tv show entertainment",
  "tv": "tv television stream display widescreen high-definition hd 1080p 4k 8k smart digital video entertainment showtime channels terrestrial satellite cable broadcast",
  "radio": "radio signal broadcast connectivity live frequency",
  "mic-vocal": "mic vocal lyrics voice listen sound music radio podcast karaoke singing microphone",
  "gamepad-2": "gamepad console",
  "dices": "dices dice random tabletop board game",
  "drama": "drama masks theater theatre entertainment show",
  "book-audio": "book audio audiobook reading listening sound story fiction novel information knowledge education student study learning research",
  "disc-3": "disc album music vinyl record cd dvd format dj spin rotate rpm",
  "speaker": "speaker sound audio music tweeter subwoofer bass production producer dj",
  "projector": "projector cinema film movie home video presentation slideshow office meeting project planning",
  "aperture": "aperture camera photo pictures shutter exposure",
  "trophy": "trophy prize sports winner achievement award champion celebration victory competition tournament leaderboard ranking success reward cup first gold",
  "medal": "medal prize sports winner trophy award achievement",
  "volleyball": "volleyball beach sand net holiday vacation summer soccer football futbol kick pitch goal score bounce leather wool yarn knitting sewing thread embroidery textil",
  "goal": "goal flag bullseye",
  "joystick": "joystick game console control stick",
  "flag": "flag report marker notification warning milestone goal notice signal attention banner",
  "swords": "swords battle challenge combat conflict crossed duel faction fantasy game melee medieval opponent rivalry rpg versus weapon war warrior",
  "sword": "sword battle challenge combat duel fantasy game knight melee medieval offense rpg sharp weapon war warrior",
  "dice-5": "dice random tabletop 5 board game",
  "spade": "spade shape suit playing cards",
  "timer-reset": "timer reset time stopwatch",
  "bookmark": "bookmark save favorite mark label attachment file stick pin read clip marker tag",
  "circle": "circle off zero record shape",
  "square": "square stop playback music audio video rectangle aspect ratio 1:1 shape",
  "triangle": "triangle equilateral delta shape pyramid hierarchy",
  "hexagon": "hexagon shape node.js logo",
  "diamond": "diamond square rectangle oblique rhombus shape suit playing cards",
  "octagon": "octagon stop shape",
  "pentagon": "pentagon shape",
  "infinity": "infinity unlimited forever loop math",
  "hash": "hash hashtag number pound",
  "asterisk": "asterisk symbol sterisk mark pointer pencil sign alert notification indicator symbolic reference times multiply multiplication operator code glob pattern wildca",
  "check": "check done todo tick complete task",
  "circle-check": "circle check done todo tick complete task",
  "badge": "badge check verified unverified",
  "sun-moon": "sun moon dark light brightness theme auto theme system theme appearance",
  "moon-star": "moon star dark night",
  "orbit": "orbit planet space physics satellites moons",
  "circle-dot": "circle dot pending progress issue code coding version control choices multiple choice choose album music songs format cd dvd vinyl sleeve cover platinum compila",
  "shapes": "shapes triangle equilateral square circle classification different collection toy blocks learning",
};

/** The icons whose name or words contain every word of `query`, in the picker's order. */
export function findAreaIcons(query: string): AreaIcon[] {
  const parts = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (!parts.length) return [...AREA_ICONS];
  return AREA_ICONS.filter((icon) => parts.every((p) => icon.includes(p) || AREA_ICON_WORDS[icon].includes(p)));
}
