-- What the local app gained while the cloud schema was being written, for the cloud: a task's "Done when"
-- items; where its sessions run (a terminal or the agent's desktop app on a computer, or the provider's
-- cloud) and on which computer; what each computer found of the agents; and the reports agents hand back,
-- with the images they attach.
--
-- As in the rest of the schema, nothing here decides what runs on a computer. A task's own folder is that
-- computer's setting (src/server/device.ts), not a column. The Codex cloud environment only names where a
-- cloud task runs at OpenAI; it reaches a command line, so it is held to plain letters, digits and a few
-- separators here, and the launcher checks it again. Images stay on the computer the agent saved them on:
-- attachments records which one, and the other computers and the web app show that instead.

/* ---------- tasks, projects and sessions ---------- */

alter table public.tasks
  -- What must be true when the task is finished, one checkable outcome per item.
  add column done_when text[] not null default '{}'
    check (cardinality(done_when) <= 50 and char_length(array_to_string(done_when, '')) <= 20000),
  -- Where its sessions run; null picks the terminal when the agent's command-line tool is there, else its app.
  add column run_in text check (run_in in ('terminal', 'desktop', 'cloud')),
  -- The computer its sessions run on; null means the project's.
  add column device_id uuid,
  add foreign key (user_id, device_id) references public.devices (user_id, id) on delete set null (device_id);

alter table public.projects
  -- The computer its sessions run on; null means whichever computer starts them.
  add column device_id uuid,
  -- The Codex cloud environment (its label or id) that tasks sent to Codex cloud run in.
  add column codex_env text check (codex_env ~ '^[A-Za-z0-9][A-Za-z0-9 ._/:-]{0,99}$'),
  add foreign key (user_id, device_id) references public.devices (user_id, id) on delete set null (device_id);

alter table public.sessions
  add column surface text not null default 'terminal' check (surface in ('terminal', 'desktop', 'cloud')),
  -- Where to follow it, like a cloud task's page. Only https links, for a link in the app.
  add column url text check (url ~ '^https://[^\s<>"'']{1,1000}$');

/* ---------- what each computer found of the agents ---------- */

alter table public.devices
  -- Per agent: its command-line tool, its desktop app and whether the app reaches PacedMind. For display.
  add column agents jsonb not null default '{}' check (jsonb_typeof(agents) = 'object' and octet_length(agents::text) <= 4000),
  add column checked_at timestamptz;

grant update (agents, checked_at) on public.devices to authenticated;

/* ---------- reports and images ---------- */

-- What an agent handed back with finish_task: one per hand-back, so a session that is resumed can have several.
create table public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  session_id text not null,
  task_id bigint not null,
  outcome text not null default 'done' check (outcome in ('done', 'partial', 'blocked')),
  summary text not null check (char_length(summary) between 1 and 2000),
  -- Markdown.
  details text not null default '' check (char_length(details) <= 100000),
  -- The task's "Done when" items as the agent answered them: [{ text, verdict, note }].
  criteria jsonb not null default '[]' check (jsonb_typeof(criteria) = 'array' and jsonb_array_length(criteria) <= 50 and octet_length(criteria::text) <= 200000),
  verify jsonb not null default '[]' check (jsonb_typeof(verify) = 'array' and jsonb_array_length(verify) <= 50 and octet_length(verify::text) <= 200000),
  questions jsonb not null default '[]' check (jsonb_typeof(questions) = 'array' and jsonb_array_length(questions) <= 50 and octet_length(questions::text) <= 200000),
  -- [{ label, url }]; the app shows only http and https links.
  links jsonb not null default '[]' check (jsonb_typeof(links) = 'array' and jsonb_array_length(links) <= 50 and octet_length(links::text) <= 200000),
  -- Keys of tasks the agent created for work outside this one.
  follow_ups jsonb not null default '[]' check (jsonb_typeof(follow_ups) = 'array' and jsonb_array_length(follow_ups) <= 50 and octet_length(follow_ups::text) <= 20000),
  created_at text not null check (created_at ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$'),
  -- What you asked to change after reading it; the agent gets it through start_task.
  changes text check (char_length(changes) between 1 and 20000),
  changes_at text check (changes_at ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$'),
  unique (user_id, id),
  foreign key (user_id, session_id) references public.sessions (user_id, id) on delete cascade,
  foreign key (user_id, task_id) references public.tasks (user_id, id) on delete cascade
);

-- An image an agent attached to a task, such as a screenshot of the result. The file stays in the desktop
-- app's data folder on `device_id`, named `file`; the other computers and the web app can't show it.
create table public.attachments (
  -- Random, made by the desktop app that keeps the file.
  id text primary key check (id ~ '^[0-9a-f]{16}$'),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  task_id bigint not null,
  session_id text,
  -- The report it belongs to; null while the session is still working.
  report_id bigint,
  device_id uuid,
  file text not null check (file ~ '^[0-9a-f]{16}\.(png|jpg|gif|webp)$'),
  mime text not null check (mime in ('image/png', 'image/jpeg', 'image/gif', 'image/webp')),
  bytes integer not null check (bytes between 1 and 20971520),
  width integer check (width between 1 and 1000000),
  height integer check (height between 1 and 1000000),
  caption text not null default '' check (char_length(caption) <= 500),
  created_at text not null check (created_at ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$'),
  unique (user_id, id),
  foreign key (user_id, task_id) references public.tasks (user_id, id) on delete cascade,
  foreign key (user_id, session_id) references public.sessions (user_id, id) on delete cascade,
  foreign key (user_id, report_id) references public.reports (user_id, id) on delete set null (report_id),
  foreign key (user_id, device_id) references public.devices (user_id, id) on delete set null (device_id)
);

create index tasks_device_idx on public.tasks (user_id, device_id);
create index projects_device_idx on public.projects (user_id, device_id);
create index reports_task_idx on public.reports (user_id, task_id);
create index reports_session_idx on public.reports (user_id, session_id);
create index attachments_task_idx on public.attachments (user_id, task_id);
create index attachments_session_idx on public.attachments (user_id, session_id);
create index attachments_report_idx on public.attachments (user_id, report_id);
create index attachments_device_idx on public.attachments (user_id, device_id);

/* ---------- privileges and row level security, as for the other tables ---------- */

revoke all on public.reports, public.attachments from anon;
revoke all on sequence public.reports_id_seq from anon;
revoke truncate, references, trigger on public.reports, public.attachments from authenticated;

alter table public.reports enable row level security;
alter table public.attachments enable row level security;

create policy "Own reports" on public.reports for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Own attachments" on public.attachments for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy "Two-factor session" on public.reports as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));
create policy "Two-factor session" on public.attachments as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));

create trigger reports_bump after insert or update or delete on public.reports for each row execute function private.bump_version();
create trigger attachments_bump after insert or update or delete on public.attachments for each row execute function private.bump_version();
