-- PacedMind's cloud data. Every row belongs to one account (user_id), and the database itself enforces who
-- may read or change it, whichever client asks:
--
-- - Row level security limits every table to the signed-in account's rows.
-- - A restrictive policy on every table also requires a session that passed two-factor authentication
--   (aal2) and is still live (private.session_ok): a stolen password alone reads nothing, and a signed-out
--   or revoked session stops working at once instead of when its last token expires.
-- - References between rows include user_id, so a row can never point at another account's rows.
-- - Nothing here decides what runs on a computer. Agent commands, project folders and whether a project's
--   flow may start sessions live only in the desktop app (src/server/device.ts). Starting a session from
--   elsewhere is a request (launch_requests) that needs a two-factor code entered minutes before, and the
--   desktop app decides whether to run it.
--
-- Dates stay local wall-clock strings, as in the app (src/lib/dates.ts): "YYYY-MM-DD", "YYYY-MM-DDTHH:mm"
-- and timestamps "YYYY-MM-DDTHH:mm:ss". Checks below keep text in those shapes and within sane sizes, so
-- a compromised browser can't store values the desktop app would trip over.

/* ---------- helpers for policies (not exposed through the Data API) ---------- */

create schema private;
grant usage on schema private to authenticated;

-- The request comes from a session that passed two-factor authentication and still exists: signing out,
-- revoking a device and session time limits all end it.
create function private.session_ok() returns boolean
language sql stable security definer set search_path = '' as $$
  select coalesce(auth.jwt() ->> 'aal', '') = 'aal2'
     and exists (
       select 1 from auth.sessions s
       where s.id = nullif(auth.jwt() ->> 'session_id', '')::uuid
         and s.user_id = auth.uid()
         and (s.not_after is null or s.not_after > now())
     )
$$;

-- A second factor (authenticator code or passkey) was verified within the last `seconds`.
create function private.recent_mfa(seconds integer) returns boolean
language sql stable set search_path = '' as $$
  select exists (
    select 1
    from jsonb_array_elements(coalesce(auth.jwt() -> 'amr', '[]'::jsonb)) as a (claim)
    where a.claim ->> 'method' in ('totp', 'mfa/totp', 'webauthn', 'mfa/webauthn')
      and (a.claim ->> 'timestamp')::bigint >= extract(epoch from now())::bigint - seconds
  )
$$;

/* ---------- areas and projects ---------- */

create table public.areas (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  -- Prefix of the area's task keys, e.g. WRK in WRK-12.
  key text not null check (key ~ '^[A-Z][A-Z0-9]{1,7}$'),
  color text not null check (color ~ '^#[0-9A-Fa-f]{6}$'),
  sort integer not null default 0,
  unique (user_id, key),
  unique (user_id, id)
);

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  area_id uuid not null,
  name text not null check (char_length(name) between 1 and 120),
  -- Own color; null means the area's color is used.
  color text check (color ~ '^#[0-9A-Fa-f]{6}$'),
  start_date text check (start_date ~ '^\d{4}-\d{2}-\d{2}$'),
  target_date text check (target_date ~ '^\d{4}-\d{2}-\d{2}$'),
  -- The agent new tasks default to. Its folder and flow switch are per computer (desktop app).
  agent text check (agent in ('claude', 'codex')),
  after_project_id uuid,
  sort integer not null default 0,
  unique (user_id, id),
  check (after_project_id is distinct from id),
  -- Deleting an area deletes its projects; their tasks stay, without a project (see tasks).
  foreign key (user_id, area_id) references public.areas (user_id, id) on delete cascade,
  foreign key (user_id, after_project_id) references public.projects (user_id, id) on delete set null (after_project_id)
);

/* ---------- tasks ---------- */

create table public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  -- Left empty on insert, a trigger gives the next key of the area (or INB-n without one).
  key text not null check (key ~ '^[A-Z][A-Z0-9]{1,7}-[1-9][0-9]{0,8}$'),
  area_id uuid,
  project_id uuid,
  title text not null check (char_length(title) between 1 and 500),
  description text not null default '' check (char_length(description) <= 100000),
  status text not null default 'todo' check (status in ('backlog', 'todo', 'progress', 'review', 'done', 'canceled')),
  -- 0 none, 1 urgent, 2 high, 3 medium, 4 low.
  priority smallint not null default 0 check (priority between 0 and 4),
  due_date text check (due_date ~ '^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2})?$'),
  planned_date text check (planned_date ~ '^\d{4}-\d{2}-\d{2}$'),
  estimate_min integer not null default 60 check (estimate_min between 0 and 10080),
  labels text[] not null default '{}' check (cardinality(labels) <= 50 and char_length(array_to_string(labels, '')) <= 2000),
  reminder text check (reminder ~ '^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}(:\d{2})?)?$'),
  -- Who does it; null means the project's agent, else Claude Code.
  agent text check (agent in ('claude', 'codex', 'human')),
  sort_order integer not null default 0,
  flow_x double precision,
  flow_y double precision,
  created_at text not null check (created_at ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$'),
  updated_at text not null check (updated_at ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$'),
  completed_at text check (completed_at ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$'),
  unique (user_id, key),
  unique (user_id, id),
  foreign key (user_id, area_id) references public.areas (user_id, id) on delete set null (area_id),
  foreign key (user_id, project_id) references public.projects (user_id, id) on delete set null (project_id)
);

create table public.subtasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  task_id bigint not null,
  title text not null check (char_length(title) between 1 and 500),
  done boolean not null default false,
  sort integer not null default 0,
  foreign key (user_id, task_id) references public.tasks (user_id, id) on delete cascade
);

/* ---------- calendar ---------- */

create table public.events (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title text not null check (char_length(title) between 1 and 200),
  area_id uuid,
  -- For weekly events: the first occurrence.
  start_at text not null check (start_at ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$'),
  end_at text not null check (end_at ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$'),
  recurrence text check (recurrence in ('weekly')),
  foreign key (user_id, area_id) references public.areas (user_id, id) on delete set null (area_id)
);

/* ---------- computers with the desktop app ---------- */

-- A desktop app signed in to the account. It registers itself (register_device), and revoking it
-- (revoke_device) deletes its auth session, which private.session_ok then rejects at once.
create table public.devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  platform text not null check (platform in ('windows', 'macos', 'linux')),
  -- The auth session the device is signed in with, so revoking the device can end it.
  auth_session_id uuid,
  -- For display only: what the device does with requests from elsewhere. The desktop app keeps the real
  -- setting on the computer and never reads this one back.
  remote_start text not null default 'ask' check (remote_start in ('off', 'ask', 'auto')),
  created_at timestamptz not null default now(),
  last_seen_at timestamptz,
  revoked_at timestamptz,
  unique (user_id, id)
);

/* ---------- agent sessions and flows ---------- */

create table public.sessions (
  -- Random, made by the desktop app (it also names the session's folder there).
  id text primary key check (id ~ '^[0-9a-f]{16}$'),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  task_id bigint not null,
  agent text not null check (agent in ('claude', 'codex')),
  -- The computer the session runs on.
  device_id uuid,
  -- Where it ran, for display. Starting or resuming a session never reads it: the desktop app uses its
  -- own folder for the project.
  folder text check (char_length(folder) <= 1000),
  branch text check (char_length(branch) <= 200),
  status text not null check (status in ('starting', 'running', 'finished', 'done', 'closed', 'failed')),
  started_at text not null check (started_at ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$'),
  finished_at text check (finished_at ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$'),
  ended_at text check (ended_at ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$'),
  note text check (char_length(note) <= 2000),
  cli_session_id text check (cli_session_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'),
  continues_session_id text check (continues_session_id ~ '^[0-9a-f]{16}$'),
  unique (user_id, id),
  foreign key (user_id, task_id) references public.tasks (user_id, id) on delete cascade,
  foreign key (user_id, device_id) references public.devices (user_id, id) on delete set null (device_id)
);

create table public.session_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  session_id text not null,
  at text not null check (at ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$'),
  kind text not null check (kind ~ '^[a-z_]{1,40}$'),
  text text not null default '' check (char_length(text) <= 2000),
  foreign key (user_id, session_id) references public.sessions (user_id, id) on delete cascade
);

-- A connection in a flow, which is also a dependency on the timeline: to_task waits for from_task.
create table public.edges (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  from_task_id bigint not null,
  to_task_id bigint not null,
  mode text not null default 'auto' check (mode in ('auto', 'manual', 'session', 'time')),
  at_time text check (at_time ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$'),
  unique (from_task_id, to_task_id),
  check (from_task_id <> to_task_id),
  foreign key (user_id, from_task_id) references public.tasks (user_id, id) on delete cascade,
  foreign key (user_id, to_task_id) references public.tasks (user_id, id) on delete cascade
);

-- Asks a desktop app to start a session, from the web app or another computer. Needs a two-factor code
-- entered in the last five minutes (see the insert policy), expires after ten, and the desktop app decides
-- by its own setting: never, after you allow it on that computer, or right away.
create table public.launch_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  device_id uuid not null,
  task_id bigint not null,
  agent text not null check (agent in ('claude', 'codex')),
  -- Where the request came from, for the prompt on the desktop (e.g. "the web app").
  requested_via text not null default 'web' check (requested_via ~ '^[a-z]{1,20}$'),
  requested_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '10 minutes',
  status text not null default 'pending' check (status in ('pending', 'launched', 'denied', 'expired', 'failed', 'canceled')),
  decided_at timestamptz,
  session_id text check (session_id ~ '^[0-9a-f]{16}$'),
  note text check (char_length(note) <= 500),
  foreign key (user_id, device_id) references public.devices (user_id, id) on delete cascade,
  foreign key (user_id, task_id) references public.tasks (user_id, id) on delete cascade
);

/* ---------- settings and bookkeeping ---------- */

-- Planning settings that follow the account. Everything about starting sessions (commands, terminal,
-- folders, tokens) stays on each computer.
create table public.settings (
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  key text not null,
  value jsonb not null,
  primary key (user_id, key),
  check (
    (key in ('workStart', 'workEnd', 'lunchStart', 'lunchEnd')
      and jsonb_typeof(value) = 'string' and (value #>> '{}') ~ '^([01]\d|2[0-3]):[0-5]\d$')
    or (key = 'workDays' and jsonb_typeof(value) = 'array' and jsonb_array_length(value) <= 7)
  )
);

-- The last task number used per key prefix, so keys are never handed out twice.
create table public.key_counters (
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  prefix text not null,
  last integer not null,
  primary key (user_id, prefix)
);

-- Changes on every write to an account's rows; open pages poll it to know when to refresh.
create table public.user_state (
  user_id uuid primary key references auth.users (id) on delete cascade,
  version bigint not null default 0
);

/* ---------- indexes for the references and the per-account filters ---------- */

create index projects_area_idx on public.projects (user_id, area_id);
create index projects_after_idx on public.projects (user_id, after_project_id);
create index tasks_area_idx on public.tasks (user_id, area_id);
create index tasks_project_idx on public.tasks (user_id, project_id);
create index subtasks_task_idx on public.subtasks (user_id, task_id);
create index events_area_idx on public.events (user_id, area_id);
create index devices_user_idx on public.devices (user_id);
create index sessions_task_idx on public.sessions (user_id, task_id);
create index sessions_device_idx on public.sessions (user_id, device_id);
create index session_events_session_idx on public.session_events (user_id, session_id);
create index edges_from_idx on public.edges (user_id, from_task_id);
create index edges_to_idx on public.edges (user_id, to_task_id);
create index launch_requests_device_idx on public.launch_requests (user_id, device_id, status);
create index launch_requests_task_idx on public.launch_requests (user_id, task_id);

/* ---------- privileges ---------- */

-- Nothing is readable without signing in. TRUNCATE, REFERENCES and TRIGGER are never needed by clients
-- (TRUNCATE would skip row level security).
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke truncate, references, trigger on all tables in schema public from authenticated;

-- Written only by triggers and functions.
revoke insert, update, delete on public.user_state from authenticated;
revoke insert, update on public.key_counters from authenticated;

-- Devices register through register_device (which records the auth session) and leave through
-- revoke_device (which ends it); in between only the name, the displayed remote-start setting and when it
-- was last seen change.
revoke insert, update, delete on public.devices from authenticated;
grant update (name, remote_start, last_seen_at) on public.devices to authenticated;

-- A request names the device, task and agent; the rest is set by the database. Afterwards only its outcome
-- changes.
revoke insert, update on public.launch_requests from authenticated;
grant insert (device_id, task_id, agent, requested_via) on public.launch_requests to authenticated;
grant update (status, decided_at, session_id, note) on public.launch_requests to authenticated;

/* ---------- row level security ---------- */

alter table public.areas enable row level security;
alter table public.projects enable row level security;
alter table public.tasks enable row level security;
alter table public.subtasks enable row level security;
alter table public.events enable row level security;
alter table public.devices enable row level security;
alter table public.sessions enable row level security;
alter table public.session_events enable row level security;
alter table public.edges enable row level security;
alter table public.launch_requests enable row level security;
alter table public.settings enable row level security;
alter table public.key_counters enable row level security;
alter table public.user_state enable row level security;

-- Every table: the signed-in account's own rows...
create policy "Own areas" on public.areas for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Own projects" on public.projects for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Own tasks" on public.tasks for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Own subtasks" on public.subtasks for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Own events" on public.events for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Own devices" on public.devices for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Own sessions" on public.sessions for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Own session events" on public.session_events for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Own edges" on public.edges for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Own settings" on public.settings for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Own key counters" on public.key_counters for select to authenticated
  using ((select auth.uid()) = user_id);
-- Starting over (Settings > Data) clears them.
create policy "Clear own key counters" on public.key_counters for delete to authenticated
  using ((select auth.uid()) = user_id);
create policy "Own state" on public.user_state for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Read own launch requests" on public.launch_requests for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "Settle own launch requests" on public.launch_requests for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Delete own launch requests" on public.launch_requests for delete to authenticated
  using ((select auth.uid()) = user_id);
-- Starting a session on a computer from elsewhere needs a two-factor code from the last five minutes.
create policy "Request launches with a fresh second factor" on public.launch_requests for insert to authenticated
  with check ((select auth.uid()) = user_id and (select private.recent_mfa(300)));

-- ...and only from a two-factor session that is still live.
create policy "Two-factor session" on public.areas as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));
create policy "Two-factor session" on public.projects as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));
create policy "Two-factor session" on public.tasks as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));
create policy "Two-factor session" on public.subtasks as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));
create policy "Two-factor session" on public.events as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));
create policy "Two-factor session" on public.devices as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));
create policy "Two-factor session" on public.sessions as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));
create policy "Two-factor session" on public.session_events as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));
create policy "Two-factor session" on public.edges as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));
create policy "Two-factor session" on public.launch_requests as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));
create policy "Two-factor session" on public.settings as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));
create policy "Two-factor session" on public.key_counters as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));
create policy "Two-factor session" on public.user_state as restrictive for all to authenticated
  using ((select private.session_ok())) with check ((select private.session_ok()));

/* ---------- triggers ---------- */

-- Gives a new task the next key of its area: WRK-1, WRK-2… (INB-n without an area). A key that comes
-- with the row (an import) is kept, and later keys continue after it.
create function private.assign_task_key() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  v_prefix text;
  v_n integer;
begin
  if new.key is null or new.key = '' then
    v_prefix := coalesce((select a.key from public.areas a where a.id = new.area_id and a.user_id = new.user_id), 'INB');
    insert into public.key_counters as c (user_id, prefix, last) values (new.user_id, v_prefix, 1)
      on conflict (user_id, prefix) do update set last = c.last + 1
      returning c.last into v_n;
    new.key := v_prefix || '-' || v_n;
  else
    v_prefix := split_part(new.key, '-', 1);
    v_n := split_part(new.key, '-', 2)::integer;
    insert into public.key_counters as c (user_id, prefix, last) values (new.user_id, v_prefix, v_n)
      on conflict (user_id, prefix) do update set last = greatest(c.last, excluded.last);
  end if;
  return new;
end $$;

create trigger tasks_assign_key before insert on public.tasks
  for each row execute function private.assign_task_key();

-- A project's tasks always live in the project's area.
create function private.project_area_follows() returns trigger
language plpgsql set search_path = '' as $$
begin
  update public.tasks set area_id = new.area_id where user_id = new.user_id and project_id = new.id;
  return null;
end $$;

create trigger projects_area_follows after update of area_id on public.projects
  for each row when (new.area_id is distinct from old.area_id) execute function private.project_area_follows();

-- A request gets its times and status from the database, and only for a device that is still signed in.
-- A handful of pending requests at a time is plenty for one person.
create function private.launch_request_defaults() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if not exists (select 1 from public.devices d where d.id = new.device_id and d.user_id = new.user_id and d.revoked_at is null) then
    raise exception 'That computer is signed out of PacedMind.' using errcode = '42501';
  end if;
  if (select count(*) from public.launch_requests r
      where r.user_id = new.user_id and r.status = 'pending' and r.expires_at > now()) >= 10 then
    raise exception 'Too many session requests are waiting. Wait for them to start or expire.' using errcode = '54000';
  end if;
  new.requested_at := now();
  new.expires_at := now() + interval '10 minutes';
  new.status := 'pending';
  new.decided_at := null;
  new.session_id := null;
  new.note := null;
  return new;
end $$;

create trigger launch_requests_defaults before insert on public.launch_requests
  for each row execute function private.launch_request_defaults();

-- Bumps the account's version after any write, for live refresh.
create function private.bump_version() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  v_user uuid;
begin
  if tg_op = 'DELETE' then v_user := old.user_id; else v_user := new.user_id; end if;
  insert into public.user_state as s (user_id, version) values (v_user, 1)
    on conflict (user_id) do update set version = s.version + 1;
  return null;
end $$;

create trigger areas_bump after insert or update or delete on public.areas for each row execute function private.bump_version();
create trigger projects_bump after insert or update or delete on public.projects for each row execute function private.bump_version();
create trigger tasks_bump after insert or update or delete on public.tasks for each row execute function private.bump_version();
create trigger subtasks_bump after insert or update or delete on public.subtasks for each row execute function private.bump_version();
create trigger events_bump after insert or update or delete on public.events for each row execute function private.bump_version();
-- Not for last_seen_at, which the desktop app updates every minute.
create trigger devices_bump after insert or delete or update of name, remote_start, revoked_at on public.devices for each row execute function private.bump_version();
create trigger sessions_bump after insert or update or delete on public.sessions for each row execute function private.bump_version();
create trigger session_events_bump after insert or update or delete on public.session_events for each row execute function private.bump_version();
create trigger edges_bump after insert or update or delete on public.edges for each row execute function private.bump_version();
create trigger launch_requests_bump after insert or update or delete on public.launch_requests for each row execute function private.bump_version();
create trigger settings_bump after insert or update or delete on public.settings for each row execute function private.bump_version();

-- A new account starts with the five default areas (src/server/account.ts has the same list).
create function private.handle_new_user() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.areas (user_id, name, key, color, sort) values
    (new.id, 'Work', 'WRK', '#7D93B5', 0),
    (new.id, 'Personal', 'PER', '#7FA894', 1),
    (new.id, 'Health', 'HLT', '#B08A9B', 2),
    (new.id, 'Learning', 'LRN', '#9C93B8', 3),
    (new.id, 'Dev', 'DEV', '#7AA3AD', 4);
  insert into public.user_state (user_id, version) values (new.id, 0) on conflict do nothing;
  return new;
end $$;

create trigger on_auth_user_created after insert on auth.users
  for each row execute function private.handle_new_user();

/* ---------- functions the app calls ---------- */

-- Registers the desktop app signed in with this session, and returns the device's id. At most 20 devices
-- that are still signed in.
create function public.register_device(device_name text, device_platform text) returns uuid
language plpgsql security definer set search_path = '' as $$
declare
  v_id uuid;
begin
  if not private.session_ok() then
    raise exception 'Sign in with two-factor authentication first.' using errcode = '42501';
  end if;
  if (select count(*) from public.devices d where d.user_id = auth.uid() and d.revoked_at is null) >= 20 then
    raise exception 'Too many computers are signed in. Sign one out in Settings first.' using errcode = '54000';
  end if;
  insert into public.devices (user_id, name, platform, auth_session_id, last_seen_at)
    values (auth.uid(), device_name, device_platform, (auth.jwt() ->> 'session_id')::uuid, now())
    returning id into v_id;
  return v_id;
end $$;

-- The desktop app signed in again, with a new auth session: revoking the device must end that one.
create function public.claim_device(device uuid) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not private.session_ok() then
    raise exception 'Sign in with two-factor authentication first.' using errcode = '42501';
  end if;
  update public.devices
    set auth_session_id = (auth.jwt() ->> 'session_id')::uuid, last_seen_at = now()
    where id = device and user_id = auth.uid() and revoked_at is null;
  if not found then
    raise exception 'This computer was signed out of PacedMind.' using errcode = 'P0002';
  end if;
end $$;

-- Signs a computer out: deletes its auth session, so every token of it stops working at once
-- (private.session_ok), and cancels the requests waiting for it.
create function public.revoke_device(device uuid) returns void
language plpgsql security definer set search_path = '' as $$
declare
  v_session uuid;
begin
  if not private.session_ok() then
    raise exception 'Sign in with two-factor authentication first.' using errcode = '42501';
  end if;
  update public.devices set revoked_at = now()
    where id = device and user_id = auth.uid() and revoked_at is null
    returning auth_session_id into v_session;
  if not found then
    raise exception 'That computer is already signed out.' using errcode = 'P0002';
  end if;
  if v_session is not null then
    delete from auth.sessions where id = v_session and user_id = auth.uid();
  end if;
  update public.launch_requests set status = 'canceled', decided_at = now(), note = 'The computer was signed out'
    where device_id = device and user_id = auth.uid() and status = 'pending';
end $$;

-- Deletes the account with all its data. Needs a two-factor code from the last five minutes.
create function public.delete_account() returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not private.session_ok() or not private.recent_mfa(300) then
    raise exception 'Enter a current two-factor code first.' using errcode = '42501';
  end if;
  delete from auth.users where id = auth.uid();
end $$;

revoke execute on all functions in schema private from public, anon, authenticated;
grant execute on function private.session_ok() to authenticated;
grant execute on function private.recent_mfa(integer) to authenticated;
revoke execute on function public.register_device(text, text), public.claim_device(uuid), public.revoke_device(uuid), public.delete_account()
  from public, anon;
grant execute on function public.register_device(text, text), public.claim_device(uuid), public.revoke_device(uuid), public.delete_account()
  to authenticated;
