-- Preferences: how the user likes to work, in their own words (when to plan what, dates and deadlines, how to write
-- tasks, where work goes, which agent does what). Agents read them before they plan or create tasks (get_preferences,
-- get_overview), and add to them once the user said so (update_preferences). Planning data like the rest: two-factor
-- sessions and approved agents read and write it; a session PacedMind started only reads it (its token's tools).
-- One line of plain text each, on one of six topics, at most 100 per account.

create table public.preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  topic text not null check (topic in ('schedule', 'deadlines', 'tasks', 'places', 'agents', 'other')),
  text text not null check (char_length(text) between 1 and 500 and text !~ '[[:cntrl:]]' and text = btrim(text)),
  -- Who wrote it last: the user in PacedMind, or an agent over MCP.
  source text not null default 'you' check (source in ('you', 'agent')),
  updated_at text not null check (updated_at ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$'),
  unique (user_id, id)
);

create index preferences_user_idx on public.preferences (user_id);

-- At most 100 per account, so a runaway agent can't fill the list every other agent reads.
create function private.preferences_limit() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if (select count(*) from public.preferences p where p.user_id = new.user_id) >= 100 then
    raise exception 'At most 100 preferences: change or remove some first.' using errcode = '23514';
  end if;
  return new;
end $$;

create trigger preferences_limit before insert on public.preferences
  for each row execute function private.preferences_limit();
create trigger preferences_bump after insert or update or delete on public.preferences
  for each row execute function private.bump_version();
create trigger preferences_require_cloud before insert or update on public.preferences
  for each statement execute function private.require_cloud();

revoke all on public.preferences from anon;
revoke insert, update, delete, truncate, references, trigger on public.preferences from authenticated;
grant insert (topic, text, source, updated_at) on public.preferences to authenticated;
grant update (topic, text, source, updated_at) on public.preferences to authenticated;
grant delete on public.preferences to authenticated;

alter table public.preferences enable row level security;

create policy "Own preferences" on public.preferences for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Two-factor session" on public.preferences as restrictive for all to authenticated
  using ((select private.session_ok()) or (select private.agent_ok()))
  with check ((select private.session_ok()) or (select private.agent_ok()));
